apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-webui
spec:
  selector:
    matchLabels:
      app: platform-webui
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: platform-webui
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: workingnode
      #           operator: In
      #           values: ["true"]
      containers:
      - name: platform-webui
        image: guoqiangqi/platform-webui:test
        imagePullPolicy: Always
        ports:
        - containerPort: 80

