apiVersion: v1
kind: Service
metadata:
  name: platform-webui
  labels:
    run: platform-webui
spec:
  ports:
  - port: 80
    nodePort: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: platform-webui
  type: NodePort
